site_name: AlphaGenome Notes
site_url: https://younghoonNa.github.io/AlphaGenome-notes/
site_description: AlphaGenome paper notes
site_author: Younghoon Na
repo_url: https://github.com/younghoonNa/AlphaGenome-notes
repo_name: younghoonNa/AlphaGenome-notes

theme:
  name: material
  language: ko
  logo: assets/DNA_logo_png.png
  favicon: assets/DNA_logo_png.png
  palette:
    - scheme: default
      primary: indigo
      accent: blue
  features:
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Author Info:
      - Core Authors: author-info.md
  - Introduction:
      - Overview: introduction/index.md
      - 1. Regulatory variants: introduction/01-regulatory-variants.md
      - 2. Context-resolution trade-off: introduction/02-context-resolution-tradeoff.md
      - 3. Multi-task trade-off: introduction/03-multitask-tradeoff.md
  - Figures:
      - Figure 1 - Model Architecture & Training Info:
          - Overview: figures/figure1.md
          - Panel A: figures/figure1-panel-a.md
          - Panel A Supplementary Notes: figures/figure1-panel-a-supplementary.md
          - Panel B & C: figures/figure1-panel-bc.md
          - Panel D & E: figures/figure1-panel-d.md
      - Figure 2 - Qualitative & Quantitative Analysis:
          - Overview: figures/figure2.md
      - Figure 3: figures/figure3.md
      - Figure 4: figures/figure4.md
      - Figure 5: figures/figure5.md
      - Figure 6: figures/figure6.md
      - Figure 7: figures/figure7.md
  - Background:
      - Regulatory variants: background/regulatory-variants.md
      - Non-coding variants: background/noncoding-variants.md
      - Sequence to function: background/sequence-to-function.md
      - ISM: concepts/ism.md
      - eQTL and GWAS: concepts/eqtl-gwas.md
      - Credible set and PIP: concepts/credible-set-pip.md
  - Key points:
      - Modeling points: concepts/modeling-points.md
  - References:
      - Overview: references.md
